spring:
  config:
    name: AIcoding-helper
  datasource:
    url: jdbc:mysql://localhost:3306/ai_coding_helper?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: <your-username>
    password: <your-password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: <your-key>
        model-name: <your-model>
      embedding-model:
        api-key: <your-key>
        model-name: <your-embedding-model>
      streaming-chat-model:
        model-name: <your-model>
        api-key: <your-key>

server:
  port: 8081
  servlet:
    context-path: /api

agent:
  default-tenant-id: 1
