spring:
  config:
    name: AIcoding-helper
  datasource:
    url: jdbc:mysql://localhost:3306/ai_coding_helper?useUnicode=true&amp&characterEncoding=utf8&amp&useSSL=false&amp&serverTimezone=Asia/Shanghai
    username: <your-username>
    password: <your-password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: <your-key>
        model-name: <your-model>
      embedding-model:
        api-key: <your-key>
        model-name: <your-embedding-model>
      streaming-chat-model:
        model-name: <your-model>
        api-key: <your-key>
bigmodel:
  api-key: <your-bigmodel-key>
server:
  port: 8081
  servlet:
    context-path: /api
